services:
  reverse-proxy:
    image: nginx:1.28.1
    container_name: phpipam-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - phpipam-web
    restart: unless-stopped
    
  phpipam-web:
    image: phpipam/phpipam-www:v1.7.4
    environment:
      TZ: ${TZ}
      IPAM_DATABASE_HOST: ${IPAM_DATABASE_HOST}
      IPAM_DATABASE_PASS: ${IPAM_DATABASE_PASS}
      IPAM_DATABASE_WEBHOST: ${IPAM_DATABASE_WEBHOST}
      IPAM_TRUST_X_FORWARDED: ${IPAM_TRUST_X_FORWARDED}
      IPAM_DISABLE_INSTALLER: ${IPAM_DISABLE_INSTALLER}
    restart: unless-stopped
    volumes:
      - phpipam-logo:/phpipam/css/images/logo
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:v1.7.4
    environment:
      TZ: ${TZ}
      IPAM_DATABASE_HOST: ${IPAM_DATABASE_HOST}
      IPAM_DATABASE_PASS: ${IPAM_DATABASE_PASS}
      SCAN_INTERVAL: ${SCAN_INTERVAL}
    restart: unless-stopped
    volumes:
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb

  phpipam-mariadb:
    image: mariadb:12.1.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    restart: unless-stopped
    volumes:
      - phpipam-db-data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      # https://mariadb.com/kb/en/using-healthcheck-sh/#compose-file-example
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} || exit 1"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  phpipam-db-data:
  phpipam-logo:
  phpipam-ca:
