# WARNING: Replace the example passwords with secure secrets.
# WARNING: 'my_secret_phpipam_pass' and 'my_secret_mysql_root_pass'
services:
  phpipam-web:
    image: phpipam/phpipam-www:latest
    ports:
      - "80:80"
    environment:
      TZ: ${TZ}
      IPAM_DATABASE_HOST: ${IPAM_DATABASE_HOST}
      IPAM_DATABASE_PASS: ${IPAM_DATABASE_PASS}
      IPAM_DATABASE_WEBHOST: ${IPAM_DATABASE_WEBHOST}
      IPAM_DISABLE_INSTALLER: 1
    restart: unless-stopped
    volumes:
      - phpipam-logo:/phpipam/css/images/logo
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb

  phpipam-cron:
    image: phpipam/phpipam-cron:latest
    environment:
      TZ: ${TZ}
      IPAM_DATABASE_HOST: ${IPAM_DATABASE_HOST}
      IPAM_DATABASE_PASS: ${IPAM_DATABASE_PASS}
      SCAN_INTERVAL: 5m
    restart: unless-stopped
    volumes:
      - phpipam-ca:/usr/local/share/ca-certificates:ro
    depends_on:
      - phpipam-mariadb

  phpipam-mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    restart: unless-stopped
    volumes:
      - phpipam-db-data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      # https://mariadb.com/kb/en/using-healthcheck-sh/#compose-file-example
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 1s
      retries: 5

volumes:
  phpipam-db-data:
  phpipam-logo:
  phpipam-ca:
